//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chetchik.Resources
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chetchikEntities : DbContext
    {
        public chetchikEntities()
            : base("name=chetchikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Адрес> Адрес { get; set; }
        public virtual DbSet<ВидСчетчика> ВидСчетчика { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Квитанция> Квитанция { get; set; }
        public virtual DbSet<ЛичныеДанные> ЛичныеДанные { get; set; }
        public virtual DbSet<Оплаты> Оплаты { get; set; }
        public virtual DbSet<Показания> Показания { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Статус> Статус { get; set; }
        public virtual DbSet<Счета> Счета { get; set; }
        public virtual DbSet<СчетаВКвитанциях> СчетаВКвитанциях { get; set; }
    }
}
