//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chetchik.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Квитанция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Квитанция()
        {
            this.СчетаВКвитанциях = new HashSet<СчетаВКвитанциях>();
        }
    
        public int Айди { get; set; }
        public Nullable<int> АйдиЛичныхДанных { get; set; }
        public Nullable<int> АйдиАдреса { get; set; }
        public Nullable<int> АйдиОплаты { get; set; }
    
        public virtual Адрес Адрес { get; set; }
        public virtual ЛичныеДанные ЛичныеДанные { get; set; }
        public virtual Оплаты Оплаты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СчетаВКвитанциях> СчетаВКвитанциях { get; set; }
    }
}
