//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chetchik.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Показания
    {
        public int Айди { get; set; }
        public int КубическиеМетры { get; set; }
        public System.DateTime Дата { get; set; }
        public int АйдиПользователя { get; set; }
        public int АйдиВидаСчетчика { get; set; }
        public int АйдиСчета { get; set; }
    
        public virtual ВидСчетчика ВидСчетчика { get; set; }
        public virtual Пользователь Пользователь { get; set; }
        public virtual Счета Счета { get; set; }
    }
}
