//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chetchik.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public int Айди { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public int АйдиДожности { get; set; }
        public int АйдиЛичныхДанных { get; set; }
    
        public virtual Должность Должность { get; set; }
        public virtual ЛичныеДанные ЛичныеДанные { get; set; }
    }
}
